# Site
name: "Trololó de Mulher"
description: "Trololó de Mulher"
meta_description: "Trololó de Mulher"
content_lang: "pt-br"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'UA-11722414-61'
disqus: 'trololodemulher'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=XZS5be86f1cda105300172a2f10&product=sticky-share-buttons"></script>'
enable_jumbotron_header: false
enable_jumbotron_footer: false
enable_alertbar: false
enable_explorer: false



# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache  
  
# - jekyll-mentions  
# - jemoji
# - jekyll-redirect-from
# - jekyll-avatar

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'    

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge

include: ['_pages']

permalink: /:title
