# Site
#=============================================
title: "Trolol贸 de Mulher"
description: "Trolol贸 de Mulher"
meta_description: "Trolol贸 de Mulher"
content_lang: "pt-BR"
logo: '/assets/images/favicon/favicon-32x32.png?v=2'
#favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'UA-11722414-61'
disqus: 'trololodemulher'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5bf83305a0286b00115a8d0d&product=sticky-share-buttons" async="async"></script>'
enable_jumbotron_header: false
enable_jumbotron_footer: false
enable_alertbar: false
enable_explorer: false

# Authors
#=============================================
authors:
  Lidiane:
    name: Lidiane
    display_name: "Lidiane Vasconcelos"
    description: "--"    
    email: trololomulher@gmail.com
    web: https://www.trololodemulher.com.br
    twitter: TrololodeMulher
    facebook: lidiane.vasconcelos.94
    googleplus_code: 112795712529273089482
    googleplus_id: +LidianeVasconcelosTMDC
    image: http://Lidiane-Vasconcelos.github.io/foto.jpg   
    gravatar: 94e312457714a8b53f0348c17f5f79b4
    description: "--"


# Plugins
#=============================================
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-include-cache  
  - jekyll-feed
  
  
  # jekyll-sitemap

# Archives
#=============================================
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'    

# Pagination
#=============================================
paginate: 6
paginate_path: /page:num/

# Other
#=============================================
markdown: kramdown
highlighter: rouge

include: ['_pages']

permalink: /:title
page_permalink: /:title


# Verification Tokens:
#=============================================
google_verify: 6GcW4Xv_-zM0VrPiBFV6ZbRiBxTFqnqCKss0FhVpgQk
yandex_verify: d4297441f24b3cef
bing_verify: 9364933C71A3EB51D875FC6DAAC58033
pinterest_verify: b67c53ad4b8f419348c53d1a41256265

#Social Media
#=============================================
facebook:
  admins: lidiane.vasconcelos.94
  admin_id: 1877953365614881
  publisher: TrololoMulher
  app_id: 716605308724809
twitter:
  username:  TrololoMulher
google:
  googleplus_code: 112795712529273089482
  googleplus_id: +LidianeVasconcelosTMDC


#Icons & Colors
#=============================================
theme_color:
background_color:

#Manifest
#=============================================
manifest_name: "Trolol贸 de Mulher"
manifest_short_name: "T. de Mulher" # Appears in "Add to home screen" dialogues and may have other importance also
manifest_lang: pt-br
manifest_background_color: white
manifest_theme_color: white
manifest_display: standalone
